### ISSUE TITLE
Flaticon?

### ISSUE THREAD

**Issue by kelvinelove** [kudapara/curated-design-tools#16]
Wanted to add [Flaticon](https://www.flaticon.com/) as an icons source, but didn't know whether to add it (since you did reference Flaticons but as a source of just patterns), to add it under SVG icons (since it allows you to get icons in other formats other than just as scalable vector graphics), or to create a whole separate category of just "Icons"?

**Comment by kudapara** [comment]
You can add flaticons to the svg section. All you have to do is to link up to the url that shows the svg icons.
look at what I did with Mixkit for videos and illustrations.
